# themes from https://github.com/alacritty/alacritty-theme

import = ["/Users/kolia/.config/alacritty/themes/themes/gruvbox_dark.toml"]

live_config_reload = true

[font]
size = 17

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[window]
decorations = "None"
opacity = 0.97
# startup_mode = "Fullscreen"

[window.padding]
x = 10
y = 3

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
term = "xterm-256color"

