# themes from https://github.com/alacritty/alacritty-theme

import = ["/Users/kolia/.config/alacritty/themes/themes/gruvbox_dark.toml"]

live_config_reload = true

[font]
size = 17

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

# [font.bold]
# family = "MesloLGS NF Bold"
# style = "Bold"
#
# # [font.glyph_offset]
# # x = 0
# # y = 5
#
# [font.italic]
# family = "MesloLGS NF Italic"
#
# [font.normal]
# family = "MesloLGS NF Regular"
# style = "Regular"


[window]
decorations = "None"
opacity = 1
# startup_mode = "Fullscreen"

[window.padding]
x = 10
y = 3

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
term = "xterm-256color"
