# themes from https://github.com/alacritty/alacritty-theme

import = ["/Users/na/.config/alacritty/themes/themes/gruvbox_dark.toml"]

live_config_reload = true

[font]
size = 16

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[window]
decorations = "None"
opacity = 0.98
# startup_mode = "Fullscreen"


[window.padding]
x = 10
y = 5

[cursor.style]
blinking = "Always"

[env]
term = "xterm-256color"
