#!/bin/bash
#test
# Prompt the user to choose the OS
PS3="Please select your operating system: "
options=("Mac" "Ubuntu")

select opt in "${options[@]}"; do
	case $opt in
	"Mac")
		echo "Installing packages for Mac..."
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		brew install git node yarn python pipenv postgresql redis mongodb docker docker-compose kubectl helm awscli terraform packer ansible vault consul nomad vagrant alacritty tmux bash-git-prompt
		break
		;;
	"Ubuntu")
		echo "Installing packages for Ubuntu..."
		sudo apt update
		sudo apt install -y git nodejs npm python3 python3-pip pipenv postgresql redis docker.io docker-compose ansible alacritty tmux ripgrep gh gcc g++ unzip fd-find fzf neovim

		# Install snap packages
		sudo snap install go --classic
		sudo snap install helm --classic
		sudo snap install kubectl --classic
		sudo snap install terraform --classic
		sudo snap install vault --classic
		sudo snap install nomad --classic
		sudo snap install packer --classic
		sudo snap install aws-cli --classic
		sudo snap install consul --classic
		sudo snap install lazygit --classic
		sudo snap install k9s
		
		# Symlink fd for compatibility with fd-find
		sudo ln -s $(which fdfind) /usr/local/bin/fd
		break
		;;
	*) echo "Invalid option. Please try again." ;;
	esac
done
