#!/bin/bash
set -e

while IFS= read -r package; do
  brew install "$package"
done < brewlist.txt

# Set up directories
export XDG_CONFIG_HOME="$HOME/.config"

# create dirs for configs
mkdir -p "$XDG_CONFIG_HOME/alacritty/themes"
mkdir -p "$XDG_CONFIG_HOME/k9s"

# check if alacritty themes are already cloned
if [ ! -d "$XDG_CONFIG_HOME/alacritty/themes" ]; then
git clone https://github.com/alacritty/alacritty-theme "$XDG_CONFIG_HOME/alacritty/themes"

# Create symbolic links
ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME/alacritty/alacritty.toml"
ln -sf "$PWD/k9s/skin.yml" "$XDG_CONFIG_HOME/k9s/skins/skin.yml"
ln -sf "$PWD/.bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME/nvim"
ln -sf "$PWD/starship.toml" "$XDG_CONFIG_HOME/starship.toml"
ln -sf "$PWD/yabai" "$XDG_CONFIG_HOME/yabai"
ln -sf "$PWD/skhd" "$XDG_CONFIG_HOME/skhd"
ln -sf "$PWD/sketchybar" "$XDG_CONFIG_HOME/sketchybar"


