#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Ubuntu (WSL) system and be up
# and running very quickly.

# Set up directories
export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME/bash"
mkdir -p "$XDG_CONFIG_HOME/alacritty/themes"
mkdir -p "$XDG_CONFIG_HOME/k9s"

# Clone alacritty themes
git clone https://github.com/alacritty/alacritty-theme "$XDG_CONFIG_HOME/alacritty/themes"

# Create symbolic links
ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME/alacritty/alacritty.toml"
ln -sf "$PWD/k9s/skin.yml" "$XDG_CONFIG_HOME/k9s/skins/skin.yml"
ln -sf "$PWD/.bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
# ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME/nvim"
