add_newline = false

format = """\
$directory\
$git_branch\
$git_status\
$aws\
$character\
"""

[character]
# success_symbol = '[➜](bold green)'
# error_symbol = '[➜](bold red)'
vimcmd_symbol = '[i](green)'
vimcmd_replace_one_symbol = '[r](bold green)'

[directory]
home_symbol = ''
truncation_length = 1
truncation_symbol = ''


[git_branch]
format = '[$branch]($style)'
style = "bold red"

[git_status]
format = '[($modified)]($style)'
style = "red bold"
modified = "*"

[aws]
format = "[ $profile]($style)-([$region](bold blue))"
style = 'bold yellow'
disabled = true


