add_newline = false
# command_timeout = 3000

format = """\
$directory\
$git_branch\
$git_status\
$aws\
$character\
"""

[character]
success_symbol = '[﹩](green)'
error_symbol = '[﹩](red)'

[git_branch]
format = '[$branch]($style)'
style = "bold red"

[git_status]
format = '[($modified)]($style)'
style = "red bold"
modified = "*"
#
# [aws]
# format = "[ $profile]($style)-([$region](bold blue))"
# style = 'bold yellow'
# disabled = true
