#!/bin/bash

# Define the directory where the applications list will be saved
output_file="$DOTFILES/apps.txt"

# List applications and save to a file
ls /Applications/ > "$output_file"

# Navigate to the dotfiles directory and commit the changes
cd "$DOTFILES" || exit
git add "$output_file"
git commit -m "Automated commit at $(date)"
git push
