#!/bin/bash

Applications=$(ls /Applications/)

# Save the list of applications to a file
#
echo "$Applications" > "$DOTFILES/apps.txt"

cd "$DOTFILES" || exit
git add apps.txt 
git commit -m "Automated commit at $(date)"
git push
