#!/bin/bash
export PATH="/opt/homebrew/bin:$PATH"
brew list >/Users/na/Projects/dotfiles/brewlist.txt

cd /Users/na/Projects/dotfiles || exit
git add brewlist.txt
git commit -m "Automated commit at $(date)"
git push
