#!/bin/bash

#!/bin/bash

# Max retries
retries=100

# Current retry number
retry=0

# Awaiter timeout in seconds
timeout=0

# Extract protocol from the provided address
protocol=$(echo "$2" | cut -d ':' -f 1)

echo "Protocol: $protocol"
echo "Input: $1"
echo "Output: $2"

# Determine the output format based on the protocol
if [ "$protocol" == "srt" ]; then
  output_format="mpegts"
elif [ "$protocol" == "rtmp" ]; then
  output_format="flv"
else
  echo "Unsupported protocol. Please provide either srt:// or rtmp:// address."
  exit 1
fi

# Retry the streaming process until success or maximum retries reached
until [ $retry -gt $retries ]; do
   ffmpeg -hide_banner -loglevel verbose -stream_loop -1 -re -i "$1" -vcodec copy -acodec copy -f "$output_format" "$2" && break
   ((retry++))
   sleep $timeout
done
