# bash completions for the dot command
# Auto-generated by `dot completions`; sourced from ~/.bashrc.

_dot() {
    local cur prev words cword
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local commands="init update doctor package check-packages retry-failed benchmark-shell gen-ssh-key stow completions link unlink edit help"

    # package subcommands
    if [[ $COMP_CWORD -ge 2 && "${COMP_WORDS[1]}" == "package" ]]; then
        local pkg_sub="add remove update list help"
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "$pkg_sub" -- "$cur") )
            return 0
        fi
        case "${COMP_WORDS[2]}" in
            add)
                if [[ $COMP_CWORD -eq 3 ]]; then
                    COMPREPLY=( $(compgen -W "brew cask" -- "$cur") )
                else
                    COMPREPLY=( $(compgen -W "base work" -- "$cur") )
                fi
                ;;
            remove)
                COMPREPLY=( $(compgen -W "base work auto" -- "$cur") )
                ;;
            update)
                COMPREPLY=( $(compgen -W "all base work" -- "$cur") )
                ;;
            list)
                COMPREPLY=( $(compgen -W "all base work" -- "$cur") )
                ;;
        esac
        return 0
    fi

    # init options
    if [[ $COMP_CWORD -eq 2 && "${COMP_WORDS[1]}" == "init" ]]; then
        COMPREPLY=( $(compgen -W "--skip-ssh --skip-font" -- "$cur") )
        return 0
    fi

    # benchmark-shell options
    if [[ "${COMP_WORDS[1]}" == "benchmark-shell" ]]; then
        COMPREPLY=( $(compgen -W "-r --runs -v --verbose -h --help" -- "$cur") )
        return 0
    fi

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return 0
    fi

    # global options on the first word
    if [[ $COMP_CWORD -eq 1 && "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--version -h --help" -- "$cur") )
        return 0
    fi
}

complete -F _dot dot
