export const KIRO_MODELS = [
  { id: "claude-opus-4.8", name: "Claude Opus 4.8 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 200000, maxTokens: 32000 },
  { id: "claude-opus-4.6", name: "Claude Opus 4.6 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 200000, maxTokens: 32000 },
  { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 200000, maxTokens: 16384 },
  { id: "claude-opus-4.5", name: "Claude Opus 4.5 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 200000, maxTokens: 32000 },
  { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 200000, maxTokens: 16384 },
  { id: "claude-sonnet-4", name: "Claude Sonnet 4 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 200000, maxTokens: 16384 },
  { id: "claude-haiku-4.5", name: "Claude Haiku 4.5 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 200000, maxTokens: 8192 },
  { id: "deepseek-3.2", name: "DeepSeek 3.2 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 8192 },
  { id: "minimax-m2.5", name: "MiniMax M2.5 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 8192 },
  { id: "minimax-m2.1", name: "MiniMax M2.1 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 8192 },
  { id: "glm-5", name: "GLM-5 (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 8192 },
  { id: "qwen3-coder-next", name: "Qwen3 Coder Next (Kiro)", reasoning: false, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 8192 },
  // New models added 2026-07-13
  { id: "gpt-5.6-sol", name: "GPT-5.6 Sol (Kiro)", reasoning: true, input: ["text", "image"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 272000, maxTokens: 128000 },
  { id: "gpt-5.6-terra", name: "GPT-5.6 Terra (Kiro)", reasoning: true, input: ["text", "image"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 272000, maxTokens: 128000 },
  { id: "gpt-5.6-luna", name: "GPT-5.6 Luna (Kiro)", reasoning: true, input: ["text", "image"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 272000, maxTokens: 128000 },
  { id: "claude-sonnet-5", name: "Claude Sonnet 5 (Kiro)", reasoning: true, input: ["text", "image"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 128000 },
  { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro (Kiro)", reasoning: true, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 384000 },
  { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash (Kiro)", reasoning: true, input: ["text", "image"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
  { id: "qwen3.7-plus", name: "Qwen 3.7 Plus (Kiro)", reasoning: true, input: ["text", "image"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65536 },
  { id: "glm-5.2", name: "GLM-5.2 (Kiro)", reasoning: true, input: ["text"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 131072 },
  { id: "minimax-m3", name: "MiniMax M3 (Kiro)", reasoning: true, input: ["text", "image"] as any, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 131072 },
];
